# Water Meter
#
# The blue LED tells the device is powered on (built-in on the Wemos D1 mini).

#Name of device
substitutions:
  device_name: water_meter
  friendly_name: Water meter
  time_timezone: "Europe/Amsterdam"

#Set up ESPHome
esphome:
  name: watermeter
  platform: ESP8266
  board: d1_mini

#WiFi Settings
wifi:
  ssid: !secret iotwifi
  password: !secret iotpass
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water meter Installation"
    password: !secret fallbackpass

#Enable fallback if WiFi is not found
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable over the air updates
ota:

# Status LED of ESP
status_led:
  pin: D3

# Switch to restart the watermeter
switch:
  - platform: restart
    id: switch_restart
    name: "${friendly_name} Restart"
    
# Time for uptime
time:
  - platform: homeassistant
    id: time_homeassistant
    timezone: "${time_timezone}"
    on_time_sync:
      - component.update: sensor_uptime_timestamp
      
  - platform: sntp
    id: time_sntp
    timezone: "${time_timezone}"
  
sensor:
  #Wifi signal
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 300s
    id: sensor_wifi_signal
     
  - platform: uptime
    id: sensor_uptime
    
  # Uptime Timestamp Sensor
  - platform: template
    id: sensor_uptime_timestamp
    name: "${friendly_name} Uptime"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(time_homeassistant).utcnow().timestamp - id(sensor_uptime).state
      );
      return timestamp;
      
  - platform: pulse_meter
    id: sensor_pulse_meter
    name: "${friendly_name} Current Usage"
    icon: "mdi:water-pump"
    unit_of_measurement: "L/min"
    timeout: 2min
    accuracy_decimals: 1
    total:
      id: sensor_pulse_meter_total
      name: "${friendly_name} Total Consumption"
      icon: "mdi:cube-outline"
      unit_of_measurement: "m³"
      state_class: total_increasing
      device_class: water
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
    pin: D1
    
text_sensor:
  # IP address #
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP address"
      icon: "mdi:network-outline"
    ssid:
      name: "${friendly_name} Connected SSID"
    bssid:
      name: "${friendly_name} Connected BSSID"
  - platform: version
    id: text_sensor_version
    name: "${friendly_name} ESPHome Version"
